[env:bw16]
platform = file://platform
; platform = file://../../platform

board = bw16
framework = arduino
monitor_speed = 115200
platform_packages =
    framework-arduinorealtek-amebad @ file://vendor/framework-arduinorealtek-amebad-3.1.9-bundle.tar.gz
    toolchain-realtek-amebad @ file://vendor/toolchain-realtek-amebad-windows-1.0.1-bundle.tar.gz
    tool-realtek-amebad @ file://vendor/tool-realtek-amebad-windows-1.1.3-bundle.tar.gz
    platformio/tool-scons @ file://vendor/tool-scons-4.40801.0-bundle.tar.gz

; Uncomment and change this if PlatformIO selects the wrong serial port.
; upload_port = COM5

; Use 921600 if your USB-to-serial bridge is unstable at 1500000 baud.
board_upload.speed = 1500000

; Auto Upload BW16
board_upload.auto_mode = Enable

